apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "boldbi.labels" . | nindent 4 }}
  name: bold-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  widget_bing_map_enable_secret: "{{ $.Values.bingMapWidget.enabled }}"
  widget_bing_map_api_key_secret: "{{ $.Values.bingMapWidget.apiKey }}"