apiVersion: v1
kind: Secret
metadata:
  name: bold-services-azure-secret
  namespace: bold-services
type: Opaque
data:
  azurestorageaccountname: <base64_azurestorageaccountname>
  azurestorageaccountkey: <base64_azurestorageaccountkey>
---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: bold-services-fileserver
 namespace: bold-services
spec:
 capacity:
   storage: 3Gi
 accessModes:
 - ReadWriteMany
 persistentVolumeReclaimPolicy: Retain
 storageClassName: azurefile
 azureFile:
   secretName: bold-services-azure-secret
   shareName: <file_share_name>
   readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: bold-services-fileserver-claim
 namespace: bold-services
spec:
 accessModes:
 - ReadWriteMany
 storageClassName: azurefile
 volumeName: bold-services-fileserver
 resources:
   requests:
     storage: 3Gi